name: master branch CI/CD
on:
  push:
    branches:
      - master
permissions:
  packages: write
jobs:
  BUILD-AND-PUSH-IMAGE:
    runs-on: ubuntu-latest

    steps:
      - name: CHECK-OUT-BRANCH
        uses: actions/checkout@v3
      - name: SETUP-JDK
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: LOG-IN-TO-THE-REGISTRY
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN}}
      - name: GRANT-EXECUTE-PERMISSION-FOR-GRADLEW
        run: chmod +x gradlew
      - name: Build with Gradle
        run: |
          ./gradlew jib \
          -Djib.to.image=ghcr.io/maskun2/community\
  DEPLOY:
    needs: BUILD-AND-PUSH-IMAGE
    runs-on:  self-hosted
    steps:
      - name: LOGIN-TO-GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Docker run
        run: |
          docker pull ghcr.io/maskun2/community
          sudo docker-compose down
          sudo docker-compose up -d